version: '3.7'
services:
    db:
        image: postgres:latest
        container_name: dhBot
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
        - database_data:/var/lib/postgresql/data

volumes:
    database_data:
        driver: local